id: A14954720
title: Essence and Embodiment of All the Buddhas
type: translation
pechas:
- I7AA0C174
- I64A2D662
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:49.667911
  last_modified_at: 2023-01-04 11:48:49.667922
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I7AA0C174/5FB9: BCC6
  I64A2D662/0B25: BCC6
